"use strict";

export const CSS_MARKDOWN_STYLE_RULE_NAME = "css";
export const NAME_MARKDOWN_STYLE_RULE_NAME = "name";
export const VALUE_MARKDOWN_STYLE_RULE_NAME = "value";
export const CLASS_MARKDOWN_STYLE_RULE_NAME = "class";
export const ERROR_MARKDOWN_STYLE_RULE_NAME = "error";
export const AMOUNT_MARKDOWN_STYLE_RULE_NAME = "amount";
export const TARGET_MARKDOWN_STYLE_RULE_NAME = "target";
export const STRING_MARKDOWN_STYLE_RULE_NAME = "string";
export const COLOUR_MARKDOWN_STYLE_RULE_NAME = "colour";
export const VALUES_MARKDOWN_STYLE_RULE_NAME = "values";
export const CONTENT_MARKDOWN_STYLE_RULE_NAME = "content";
export const DOCUMENT_MARKDOWN_STYLE_RULE_NAME = "document";
export const NONSENSE_MARKDOWN_STYLE_RULE_NAME = "nonsense";
export const ARGUMENT_MARKDOWN_STYLE_RULE_NAME = "argument";
export const SELECTOR_MARKDOWN_STYLE_RULE_NAME = "selector";
export const RULE_SET_MARKDOWN_STYLE_RULE_NAME = "ruleSet";
export const VERBATIM_MARKDOWN_STYLE_RULE_NAME = "verbatim";
export const RULE_NAME_MARKDOWN_STYLE_RULE_NAME = "ruleName";
export const SELECTORS_MARKDOWN_STYLE_RULE_NAME = "selectors";
export const ARGUMENTS_MARKDOWN_STYLE_RULE_NAME = "arguments";
export const IDENTIFIER_MARKDOWN_STYLE_RULE_NAME = "identifier";
export const DECLARATION_MARKDOWN_STYLE_RULE_NAME = "declaration";
export const PSEUDO_CLASS_MARKDOWN_STYLE_RULE_NAME = "pseudoClass";
export const SELECTORS_LIST_MARKDOWN_STYLE_RULE_NAME = "selectorsList";

const markdownStyleRuleNames = {
  CSS_MARKDOWN_STYLE_RULE_NAME,
  NAME_MARKDOWN_STYLE_RULE_NAME,
  VALUE_MARKDOWN_STYLE_RULE_NAME,
  CLASS_MARKDOWN_STYLE_RULE_NAME,
  ERROR_MARKDOWN_STYLE_RULE_NAME,
  AMOUNT_MARKDOWN_STYLE_RULE_NAME,
  TARGET_MARKDOWN_STYLE_RULE_NAME,
  STRING_MARKDOWN_STYLE_RULE_NAME,
  COLOUR_MARKDOWN_STYLE_RULE_NAME,
  VALUES_MARKDOWN_STYLE_RULE_NAME,
  CONTENT_MARKDOWN_STYLE_RULE_NAME,
  DOCUMENT_MARKDOWN_STYLE_RULE_NAME,
  NONSENSE_MARKDOWN_STYLE_RULE_NAME,
  ARGUMENT_MARKDOWN_STYLE_RULE_NAME,
  SELECTOR_MARKDOWN_STYLE_RULE_NAME,
  RULE_SET_MARKDOWN_STYLE_RULE_NAME,
  VERBATIM_MARKDOWN_STYLE_RULE_NAME,
  RULE_NAME_MARKDOWN_STYLE_RULE_NAME,
  SELECTORS_MARKDOWN_STYLE_RULE_NAME,
  ARGUMENTS_MARKDOWN_STYLE_RULE_NAME,
  IDENTIFIER_MARKDOWN_STYLE_RULE_NAME,
  DECLARATION_MARKDOWN_STYLE_RULE_NAME,
  PSEUDO_CLASS_MARKDOWN_STYLE_RULE_NAME,
  SELECTORS_LIST_MARKDOWN_STYLE_RULE_NAME
};

export default markdownStyleRuleNames;
