"use strict";

import { Query } from "occam-query";

import { LINE_RULE_NAME,
         IMAGE_RULE_NAME,
         TABLE_RULE_NAME,
         ERROR_RULE_NAME,
         ANCHOR_RULE_NAME,
         DIVISION_RULE_NAME,
         PARAGRAPH_RULE_NAME,
         HYPERLINK_RULE_NAME,
         INDEX_LIST_RULE_NAME,
         INDEX_ITEM_RULE_NAME,
         INDEX_LINK_RULE_NAME,
         TABLE_HEAD_RULE_NAME,
         TABLE_BODY_RULE_NAME,
         BLOCK_LINE_RULE_NAME,
         EMAIL_LINK_RULE_NAME,
         STRONG_TEXT_RULE_NAME,
         ORDERED_LIST_RULE_NAME,
         ORDERED_ITEM_RULE_NAME,
         INDEX_HEADING_RULE_NAME,
         BLOCK_LISTING_RULE_NAME,
         CONTENTS_LINK_RULE_NAME,
         CONTENTS_ITEM_RULE_NAME,
         CONTENTS_LIST_RULE_NAME,
         FOOTNOTE_LINK_RULE_NAME,
         VERTICAL_SPACE_RULE_NAME,
         TABLE_HEAD_ROW_RULE_NAME,
         TABLE_BODY_ROW_RULE_NAME,
         INLINE_LISTING_RULE_NAME,
         UNORDERED_LIST_RULE_NAME,
         UNORDERED_ITEM_RULE_NAME,
         FOOTNOTES_ITEM_RULE_NAME,
         FOOTNOTES_LIST_RULE_NAME,
         TABLE_HEAD_CELL_RULE_NAME,
         TABLE_BODY_CELL_RULE_NAME,
         EMPHASISED_TEXT_RULE_NAME,
         PRIMARY_HEADING_RULE_NAME,
         TERTIARY_HEADING_RULE_NAME,
         SECONDARY_HEADING_RULE_NAME,
         QUATERNARY_HEADING_RULE_NAME,
         PAGE_NUMBER_DIRECTIVE_RULE_NAME,
         STRONGLY_EMPHASISED_TEXT_RULE_NAME } from "./ruleNames";

const expressionStrings = [
        `//${LINE_RULE_NAME}`,
        `//${IMAGE_RULE_NAME}`,
        `//${TABLE_RULE_NAME}`,
        `//${ERROR_RULE_NAME}`,
        `//${ANCHOR_RULE_NAME}`,
        `//${DIVISION_RULE_NAME}`,
        `//${PARAGRAPH_RULE_NAME}`,
        `//${HYPERLINK_RULE_NAME}`,
        `//${INDEX_LIST_RULE_NAME}`,
        `//${INDEX_ITEM_RULE_NAME}`,
        `//${INDEX_LINK_RULE_NAME}`,
        `//${TABLE_HEAD_RULE_NAME}`,
        `//${TABLE_BODY_RULE_NAME}`,
        `//${BLOCK_LINE_RULE_NAME}`,
        `//${EMAIL_LINK_RULE_NAME}`,
        `//${STRONG_TEXT_RULE_NAME}`,
        `//${ORDERED_LIST_RULE_NAME}`,
        `//${ORDERED_ITEM_RULE_NAME}`,
        `//${INDEX_HEADING_RULE_NAME}`,
        `//${BLOCK_LISTING_RULE_NAME}`,
        `//${CONTENTS_LINK_RULE_NAME}`,
        `//${CONTENTS_ITEM_RULE_NAME}`,
        `//${CONTENTS_LIST_RULE_NAME}`,
        `//${FOOTNOTE_LINK_RULE_NAME}`,
        `//${VERTICAL_SPACE_RULE_NAME}`,
        `//${TABLE_HEAD_ROW_RULE_NAME}`,
        `//${TABLE_BODY_ROW_RULE_NAME}`,
        `//${INLINE_LISTING_RULE_NAME}`,
        `//${UNORDERED_LIST_RULE_NAME}`,
        `//${UNORDERED_ITEM_RULE_NAME}`,
        `//${FOOTNOTES_ITEM_RULE_NAME}`,
        `//${FOOTNOTES_LIST_RULE_NAME}`,
        `//${TABLE_HEAD_CELL_RULE_NAME}`,
        `//${TABLE_BODY_CELL_RULE_NAME}`,
        `//${EMPHASISED_TEXT_RULE_NAME}`,
        `//${PRIMARY_HEADING_RULE_NAME}`,
        `//${TERTIARY_HEADING_RULE_NAME}`,
        `//${SECONDARY_HEADING_RULE_NAME}`,
        `//${QUATERNARY_HEADING_RULE_NAME}`,
        `//${PAGE_NUMBER_DIRECTIVE_RULE_NAME}`,
        `//${STRONGLY_EMPHASISED_TEXT_RULE_NAME}`
      ],
      queries = expressionStrings.map((expressionString) => {
        const query = Query.fromExpressionString(expressionString);

        return query;
      });

export default queries;